# Generated by Django 4.1.6 on 2023-02-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
    ]
