# Generated by Django 4.1.6 on 2023-02-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['pk']},
        ),
    ]
